[server]
# Optimize for Streamlit Cloud
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
# Disable some features that can cause issues
gatherUsageStats = false

[theme]
# Default theme
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
showErrorDetails = false

[runner]
magicEnabled = false

[logger]
level = "info"
