# Streamlit Cloud Secrets Template
# Replace with your actual values in Streamlit Cloud dashboard

# IMPORTANT: This file is just a template
# Add your real secrets in the Streamlit Cloud dashboard under Settings > Secrets

# Example format (don't put real keys here):
# GEMINI_API_KEY = "your_actual_api_key_here"
# ENVIRONMENT = "production"